version: "3.8"
services:
  postgres:
    container_name: postgres_JPACA215
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: DbCA215
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_JPACA215
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@just.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5055:80"
